name: assn
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.10
  - pandas
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - transformers
  - typing-extensions
  - pip:
      - pydantic
      - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz
      - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bc5cdr_md-0.5.4.tar.gz
